name: Build
on:
  pull_request: { branches: [ main ] }
  push: { branches: [ main, feat/** ] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - run: chmod +x gradlew
      - run: ./gradlew clean build --stacktrace